version: '3.8'
services:
  purchase_dept:
    build:
      context: ./purchase_dept
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  service_dept:
    build:
      context: ./purchase_dept
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
  supervision:
    build:
      context: ./supervision_dept
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta de comunicação
      - "15672:15672" # Painel de administração (user: guest, pass: guest)

  postgres:
    image: postgres:15-alpine
    container_name: postgres_main
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      # Este banco 'postgres' é o padrão, os outros serão criados pelo script
      POSTGRES_DB: postgres 
    ports:
      - "5434:5432"
    volumes:
      # Persistência dos dados (para não perder quando reiniciar)
      - postgres_data:/var/lib/postgresql/data
      # A MÁGICA ACONTECE AQUI: Mapeamos o script para a pasta de init
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    networks:
      - minha-rede-microservicos

  # Definição dos volumes e redes
volumes:
  postgres_data:

networks:
  minha-rede-microservicos:
    driver: bridge